Nop.Plugin.Misc.FacebookShop/Components/HomePageProductsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Domain.Catalog;
using Nop.Plugin.Misc.FacebookShop.Models;
using Nop.Services.Catalog;
using Nop.Services.Directory;
using Nop.Services.Localization;
using Nop.Services.Media;
using Nop.Services.Security;
using Nop.Services.Seo;
using Nop.Services.Stores;
using Nop.Services.Tax;
using Nop.Web.Framework.Components;

namespace Nop.Plugin.Misc.FacebookShop.Components
{
    [ViewComponent(Name = "HomePageProducts")]
    public class HomePageProductsViewComponent : NopViewComponent
    {
        private readonly IAclService _aclService;
        private readonly ICurrencyService _currencyService;
        private readonly ILocalizationService _localizationService;
        private readonly IPermissionService _permissionService;
        private readonly IPictureService _pictureService;
        private readonly IPriceCalculationService _priceCalculationService;
        private readonly IPriceFormatter _priceFormatter;
        private readonly IProductService _productService;
        private readonly IStoreContext _storeContext;
        private readonly IStoreMappingService _storeMappingService;
        private readonly ITaxService _taxService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly IWorkContext _workContext;

        public HomePageProductsViewComponent(IAclService aclService,
            ICurrencyService currencyService,
            ILocalizationService localizationService,
            IPermissionService permissionService,
            IPictureService pictureService,
            IPriceCalculationService priceCalculationService,
            IPriceFormatter priceFormatter,
            IProductService productService,
            IStoreContext storeContext,
            IStoreMappingService storeMappingService,
            ITaxService taxService,
            IUrlRecordService urlRecordService,
            IWorkContext workContext)
        {
            this._aclService = aclService;
            this._currencyService = currencyService;
            this._localizationService = localizationService;
            this._permissionService = permissionService;
            this._pictureService = pictureService;
            this._priceCalculationService = priceCalculationService;
            this._priceFormatter = priceFormatter;
            this._productService = productService;
            this._storeContext = storeContext;
            this._storeMappingService = storeMappingService;
            this._taxService = taxService;
            this._urlRecordService = urlRecordService;
            this._workContext = workContext;
        }

            public IViewComponentResult Invoke()
        {
            var products = _productService.GetAllProductsDisplayedOnHomePage();
            //ACL and store mapping
            products = products.Where(p => _aclService.Authorize(p) && _storeMappingService.Authorize(p)).ToList();

            var model = PrepareProductOverviewModels(products).ToList();
            return View("~/Plugins/Misc.FacebookShop/Views/HomePageProducts.cshtml", model);
        }

        protected IEnumerable<ProductOverviewModel> PrepareProductOverviewModels(IEnumerable<Product> products,
            bool preparePriceModel = true, bool preparePictureModel = true,
            int? productThumbPictureSize = null, bool prepareSpecificationAttributes = false,
            bool forceRedirectionAfterAddingToCart = false)
        {
            if (products == null)
                throw new ArgumentNullException("products");

            var models = new List<ProductOverviewModel>();
            foreach (var product in products)
            {
                var model = new ProductOverviewModel
                {
                    Id = product.Id,
                    Name = _localizationService.GetLocalized(product, x => x.Name),
                    ShortDescription = _localizationService.GetLocalized(product, x => x.ShortDescription),
                    FullDescription = _localizationService.GetLocalized(product, x => x.FullDescription),
                    SeName = _urlRecordService.GetSeName(product),
                };
                //price
                if (preparePriceModel)
                {
                    #region Prepare product price

                    var priceModel = new ProductOverviewModel.ProductPriceModel();

                    switch (product.ProductType)
                    {
                        case ProductType.GroupedProduct:
                        {
                            #region Grouped product

                            var associatedProducts = _productService.GetAssociatedProducts(product.Id, _storeContext.CurrentStore.Id);

                            switch (associatedProducts.Count)
                            {
                                case 0:
                                {
                                    //no associated products
                                    priceModel.OldPrice = null;
                                    priceModel.Price = null;
                                    priceModel.DisableBuyButton = true;
                                    priceModel.DisableWishlistButton = true;
                                    priceModel.AvailableForPreOrder = false;
                                }
                                    break;
                                default:
                                {
                                    //we have at least one associated product
                                    priceModel.DisableBuyButton = true;
                                    priceModel.DisableWishlistButton = true;
                                    priceModel.AvailableForPreOrder = false;

                                    if (_permissionService.Authorize(StandardPermissionProvider.DisplayPrices))
                                    {
                                        //find a minimum possible price
                                        decimal? minPossiblePrice = null;
                                        Product minPriceProduct = null;
                                        foreach (var associatedProduct in associatedProducts)
                                        {
                                            //calculate for the maximum quantity (in case if we have tier prices)
                                            var tmpPrice = _priceCalculationService.GetFinalPrice(associatedProduct,
                                                _workContext.CurrentCustomer, decimal.Zero, true, int.MaxValue);
                                            if (!minPossiblePrice.HasValue || tmpPrice < minPossiblePrice.Value)
                                            {
                                                minPriceProduct = associatedProduct;
                                                minPossiblePrice = tmpPrice;
                                            }
                                        }
                                        if (minPriceProduct != null && !minPriceProduct.CustomerEntersPrice)
                                        {
                                            if (minPriceProduct.CallForPrice)
                                            {
                                                priceModel.OldPrice = null;
                                                priceModel.Price = _localizationService.GetResource("Products.CallForPrice");
                                            }
                                            else if (minPossiblePrice.HasValue)
                                            {
                                                //calculate prices
                                                decimal taxRate;
                                                decimal finalPriceBase = _taxService.GetProductPrice(minPriceProduct, minPossiblePrice.Value, out taxRate);
                                                decimal finalPrice = _currencyService.ConvertFromPrimaryStoreCurrency(finalPriceBase, _workContext.WorkingCurrency);

                                                priceModel.OldPrice = null;
                                                priceModel.Price = String.Format(_localizationService.GetResource("Products.PriceRangeFrom"), _priceFormatter.FormatPrice(finalPrice));

                                            }
                                            else
                                            {
                                                //Actually it's not possible (we presume that minimalPrice always has a value)
                                                //We never should get here
                                                Debug.WriteLine("Cannot calculate minPrice for product #{0}", product.Id);
                                            }
                                        }
                                    }
                                    else
                                    {
                                        //hide prices
                                        priceModel.OldPrice = null;
                                        priceModel.Price = null;
                                    }
                                }
                                    break;
                            }

                            #endregion
                        }
                            break;
                        default:
                        {
                            #region Simple product

                            //add to cart button
                            priceModel.DisableBuyButton = product.DisableBuyButton ||
                                                          !_permissionService.Authorize(StandardPermissionProvider.EnableShoppingCart) ||

Nop.Plugin.Misc.FacebookShop/Components/MiscFacebookShopCategoryNavigationViewComponent.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Core.Caching;
using Nop.Core.Domain.Customers;
using Nop.Plugin.Misc.FacebookShop.Infrastructure.Cache;
using Nop.Plugin.Misc.FacebookShop.Models;
using Nop.Services.Catalog;
using Nop.Services.Localization;
using Nop.Services.Seo;
using Nop.Web.Framework.Components;

namespace Nop.Plugin.Misc.FacebookShop.Components
{
    [ViewComponent(Name = "MiscFacebookShopCategoryNavigation")]
    public class MiscFacebookShopCategoryNavigationViewComponent : NopViewComponent
    {
        private readonly IStoreContext _storeContext;
        private readonly IWorkContext _workContext;
        private readonly ICacheManager _cacheManager;
        private readonly ICategoryService _categoryService;
        private readonly IUrlRecordService _urlRecordService;
        private readonly ILocalizationService _localizationService;

        public MiscFacebookShopCategoryNavigationViewComponent(IStoreContext storeContext,
            IWorkContext workContext,
            ICacheManager cacheManager,
            ICategoryService categoryService,
            IUrlRecordService urlRecordService,
            ILocalizationService localizationService)
        {
            this._storeContext = storeContext;
            this._workContext = workContext;
            this._cacheManager = cacheManager;
            this._categoryService = categoryService;
            this._urlRecordService = urlRecordService;
            this._localizationService = localizationService;
        }

        public IViewComponentResult Invoke()
        {
            var cacheKey = string.Format(ModelCacheEventConsumer.CATEGORY_NAVIGATION_MODEL_KEY,
                _workContext.WorkingLanguage.Id,
                string.Join(",", _workContext.CurrentCustomer.GetCustomerRoleIds()),
                _storeContext.CurrentStore.Id);
            var model = _cacheManager.Get(cacheKey, () => PrepareCategorySimpleModels(0, null, true).ToList());

            return View("~/Plugins/Misc.FacebookShop/Views/CategoryNavigation.cshtml", model);
        }

        protected IList<CategoryModel> PrepareCategorySimpleModels(int rootCategoryId,
            IList<int> loadSubCategoriesForIds,
            bool validateIncludeInTopMenu)
        {
            var result = new List<CategoryModel>();
            foreach (var category in _categoryService.GetAllCategoriesByParentCategoryId(rootCategoryId))
            {
                if (validateIncludeInTopMenu && !category.IncludeInTopMenu)
                {
                    continue;
                }

                var categoryModel = new CategoryModel
                {
                    Id = category.Id,
                    Name = _localizationService.GetLocalized(category, x => x.Name),
                    SeName = _urlRecordService.GetSeName(category)
                };

                //load subcategories?
                var loadSubCategories = false;
                if (loadSubCategoriesForIds == null)
                {
                    //load all subcategories
                    loadSubCategories = true;
                }
                else
                {
                    //we load subcategories only for certain categories
                    for (var i = 0; i <= loadSubCategoriesForIds.Count - 1; i++)
                    {
                        if (loadSubCategoriesForIds[i] == category.Id)
                        {
                            loadSubCategories = true;
                            break;
                        }
                    }
                }
                if (loadSubCategories)
                {
                    var subCategories =
                        PrepareCategorySimpleModels(category.Id, loadSubCategoriesForIds, validateIncludeInTopMenu);
                    categoryModel.SubCategories.AddRange(subCategories);
                }
                result.Add(categoryModel);
            }

            return result;
        }
    }
}

Nop.Plugin.Misc.FacebookShop/Components/MiscFacebookShopFooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Nop.Core;
using Nop.Plugin.Misc.FacebookShop.Models;
using Nop.Services.Localization;
using Nop.Web.Framework.Components;

namespace Nop.Plugin.Misc.FacebookShop.Components
{
    [ViewComponent(Name = "MiscFacebookShopFooter")]
    public class MiscFacebookShopFooterViewComponent : NopViewComponent
    {
        private readonly IStoreContext _storeContext;
        private readonly ILocalizationService _localizationService;

        public MiscFacebookShopFooterViewComponent(IStoreContext storeContext,
            ILocalizationService localizationService)
        {
            this._storeContext = storeContext;
            this._localizationService = localizationService;
        }

        public IViewComponentResult Invoke()
        {
            var model = new FooterModel
            {
                StoreName = _localizationService.GetLocalized(_storeContext.CurrentStore, x => x.Name)
            };

            return View("~/Plugins/Misc.FacebookShop/Views/Footer.cshtml", model);
        }
    }
}

Nop.Plugin.Misc.FacebookShop/Components/RenderCategoryLineViewComponent.cs
using System;
using Microsoft.AspNetCore.Mvc;
using Nop.Plugin.Misc.FacebookShop.Models;
using Nop.Web.Framework.Components;

namespace Nop.Plugin.Misc.FacebookShop.Components
{
    [ViewComponent(Name = "RenderCategoryLine")]
    public class RenderCategoryLineViewComponent : NopViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var data = ViewComponentContext.Arguments;
            var model = new RenderCategoryLineModel
            {
                Category = data["category"] as CategoryModel,
                Level = Convert.ToInt32(data["level"]),
                LastItem = Convert.ToBoolean(data["lastItem"])
            };
            return View("~/Plugins/Misc.FacebookShop/Views/_RenderCategoryLine.cshtml", model);
        }
    }
}

Nop.Plugin.Misc.FacebookShop/Views/Category.cshtml
@model CategoryModel
@{
    Layout = "~/Plugins/Misc.FacebookShop/Views/Layout.cshtml";
}
@using Nop.Plugin.Misc.FacebookShop.Models;
@using Nop.Web.Extensions

<div class="page category-page">
    <div class="page-title">
        <h1>@Model.Name</h1>
    </div>
    <div class="page-body">
        @*description*@
        @if (!String.IsNullOrWhiteSpace(Model.Description))
        {
            <div class="category-description">
                @Html.Raw(Model.Description)
            </div>
        }
        @*subcategories*@
        @if (Model.SubCategories.Count > 0)
        {
            <div class="sub-category-grid">
                @foreach (var item in Model.SubCategories)
                {
                    <div class="item-box">
                        <div class="sub-category-item">
                            <h2 class="title">
                                <a href="@Url.RouteUrl("Plugin.Misc.FacebookShop.Category", new { categoryId = item.Id })" title="@item.PictureModel.Title">
                                    @item.Name</a>
                            </h2>
                            <div class="picture">
                                <a href="@Url.RouteUrl("Plugin.Misc.FacebookShop.Category", new { categoryId = item.Id })" title="@item.PictureModel.Title">
                                    <img alt="@item.PictureModel.AlternateText" src="@item.PictureModel.ImageUrl" title="@item.PictureModel.Title" />
                                </a>
                            </div>
                        </div>
                    </div>
                }
            </div>
        }
        @*product list*@
        @if (Model.Products.Count > 0)
        {
            <div class="product-grid">
                @foreach (var item in Model.Products)
                {
                    <div class="item-box">
                        @Html.Partial("~/Plugins/Misc.FacebookShop/Views/ProductBox.cshtml", item)
                    </div>
                }
            </div>
        }
        <div class="pager">
            @Html.Pager(Model.PagingFilteringContext).QueryParam("pagenumber")
        </div>
    </div>
</div>

Nop.Plugin.Misc.FacebookShop/Views/CategoryNavigation.cshtml
@model List<CategoryModel>
@using Nop.Plugin.Misc.FacebookShop.Models;

@if (Model.Count > 0)
{
    <ul class="top-menu">
        @for (var i = 0; i < Model.Count; i++)
        {
            var category = Model[i];           
            @await Component.InvokeAsync("RenderCategoryLine", new {category, level = 0, lastItem = i == Model.Count - 1 })
        }
    </ul>
    
    <script type="text/javascript">
        $('li', '.top-menu').on('mouseenter', function () {
            $('a', $(this)).first().addClass('hover');
            if (!$(this).parent().hasClass('top-menu')) {
                var width = $(this).innerWidth();
                $('.sublist', $(this)).first().css('left', width + 15);
            }
            $('.sublist', $(this)).first().addClass('active');
            $('.top-menu-triangle', $(this)).addClass('active');
        });
        $('li', '.top-menu').on('mouseleave', function () {
            $('a', $(this)).first().removeClass('hover');
            $('.sublist', $(this)).first().removeClass('active');
            $('.top-menu-triangle', $(this)).removeClass('active');
        });
    </script>
}

Nop.Plugin.Misc.FacebookShop/Views/Configure.cshtml
@{
    Layout = "_ConfigurePlugin";
}

<div class="panel-group">
    <div class="panel panel-default">
        <div class="panel-heading">
            Configuration notes
        </div>
        <div class="panel-body">
            <div class="form-group">
                <h4>HTTPS requirement</h4>
                <p>
                    The server will have to be secure, i.e., have an SSL Security Certificate for the domain under which it's hosted
                </p>
                <h4>Facebook developer application</h4>
                <ul>
                    <li>
                        The first step in creating an application in Facebook. You can do by going to <a href="https://developers.facebook.com/apps/" target="_blank">https://developers.facebook.com/apps/</a>
                    </li>
                    <li>
                        Select "Page Tab" integration type
                    </li>
                    <li>
                        Enter "Page Tab Name". The displayed name of the tab in the page navigation
                    </li>
                    <li>
                        For the "Page Tab URL" field enter "http://www.yourstore.com/facebook/shop/"
                    </li>
                    <li>
                        For the "Secure Page Tab URL" field enter "https://www.yourstore.com/facebook/shop/" (same as the "Page Tab URL" but with HTTPS instead of HTTP)
                    </li>
                    <li>
                        Page Tab Width. Choose "Normal (810px)".
                    </li>
                </ul>
                <h4>Installing your iFrame application on your Fan Page</h4>
                <p>
                    Navigate to the following URL in your browser: https://www.facebook.com/dialog/pagetab?app_id=YOUR_APP_ID&next=YOUR_URL
                    <br/>
                    Replace "YOUR_APP_ID" with your App ID and "YOUR_URL" with your app's URL, both of which values are available in your app settings.
                    <br/>
                    You'll see an "Add page tab" page. After selecting your Facebook page from the pulldown menu and clicking "Add Page Tab" your iFrame app should appear on your Fan Page.
                </p>
            </div>
        </div>
    </div>
</div>

Nop.Plugin.Misc.FacebookShop/Views/Footer.cshtml
@model FooterModel
@using Nop.Plugin.Misc.FacebookShop.Models;
<div class="footer">
    @T("Content.CopyrightNotice", DateTime.Now.Year.ToString(), Model.StoreName)
</div>

Nop.Plugin.Misc.FacebookShop/Views/Header.cshtml
<div class="header">
    <div class="header-logo">
        <a href="@Url.RouteUrl("Plugin.Misc.FacebookShop.Index")" class="logo">&nbsp;</a>
    </div>
    <div class="search-box store-search-box">
        @Html.Partial("~/Plugins/Misc.FacebookShop/Views/SearchBox.cshtml")
    </div>
    @*
    do not uncomment the code below. if you need this functionality,
    then you have to implement it right in this plugin.
    otherwise, it could cause some issues (for example, render views for mobile devices)
    <div class="header-selectors-wrapper">
        <div class="tax-display-type-selector">
            @Html.Action("TaxTypeSelector", "Common")
        </div>
        <div class="currency-selector">
            @Html.Action("CurrencySelector", "Common")
        </div>
        <div class="language-selector">
            @Html.Action("LanguageSelector", "Common")
        </div>
    </div>*@
</div>

Nop.Plugin.Misc.FacebookShop/Views/HomePageProducts.cshtml
@model List<ProductOverviewModel>
@using Nop.Plugin.Misc.FacebookShop.Models;
@if (Model.Count > 0)
{
    <div class="product-grid home-page-product-grid">
        @foreach (var item in Model)
        {
            <div class="item-box">
                @Html.Partial("~/Plugins/Misc.FacebookShop/Views/ProductBox.cshtml", item)
            </div>
        }
    </div>
}

Nop.Plugin.Misc.FacebookShop/Views/Index.cshtml
@{
    Layout = "~/Plugins/Misc.FacebookShop/Views/Layout.cshtml";
}
<div class="page home-page">
    <div class="page-body">
        @await Component.InvokeAsync("HomePageProducts")
    </div>
</div>

Nop.Plugin.Misc.FacebookShop/Views/Layout.cshtml
@{
    Html.AddCssFileParts("~/Plugins/Misc.FacebookShop/Content/styles.css");
    Html.AddScriptParts("~/Plugins/Misc.FacebookShop/Scripts/jquery-1.10.2.min.js");
}
<!DOCTYPE html>
<html>
<head>
    <title>Facebook store</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    @Html.NopCssFiles(this.Url, ResourceLocation.Head, false)
    @Html.NopScripts(this.Url, ResourceLocation.Head, false)
</head>
<body>
    <div class="master-wrapper-page">
        @Html.Partial("~/Plugins/Misc.FacebookShop/Views/Header.cshtml")
        <div class="header-menu">
            @await Component.InvokeAsync("MiscFacebookShopCategoryNavigation")

        </div>
        <div class="master-wrapper-main">
            @RenderBody()
        </div>
        @await Component.InvokeAsync("MiscFacebookShopFooter")

    </div>
</body>
</html>

Nop.Plugin.Misc.FacebookShop/Views/ProductBox.cshtml
@model ProductOverviewModel
@using System.Net
@using Nop.Plugin.Misc.FacebookShop.Models;
@{
    var productUrl = Url.RouteUrl("Product", new { SeName = Model.SeName }, "http");
    //lo
}
<div class="product-item">
    <div class="picture">
        <a href="@productUrl" target="_blank" title="@Model.DefaultPictureModel.Title">
            <img alt="@Model.DefaultPictureModel.AlternateText" src="@Model.DefaultPictureModel.ImageUrl" title="@Model.DefaultPictureModel.Title" />
        </a>
    </div>
    <div class="details">
        <h2 class="product-title">
            <a href="@productUrl">@Model.Name</a>
        </h2>
        <div class="add-info">
            <div class="prices">
                @if (!string.IsNullOrEmpty(Model.ProductPrice.OldPrice))
                {
                    <span class="price old-price">@Model.ProductPrice.OldPrice</span>
                }
                <span class="price actual-price">@Model.ProductPrice.Price</span>
            </div>
            <div class="buttons">
                <a href="@productUrl" target="_blank" class="product-box-detail-button">@T("Products.Details")</a>
            </div>
            <div class="fb-like">
                @{
                    var fbProductUrl = productUrl;
                    //note that it won't be rendered on localhost
                    //uncomment the line below in order to render facebook like box even on localhost (minor hack)
                    fbProductUrl = fbProductUrl.Replace("://localhost", "://demo.nopcommerce.com");
                }
                <iframe src="//www.facebook.com/plugins/like.php?href=@Html.Raw(WebUtility.UrlEncode(fbProductUrl))&amp;width=100&amp;height=21&amp;colorscheme=light&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;send=false&amp;appId=159953744080931" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:100px; height:21px;" allowTransparency="true"></iframe>
            </div>
        </div>
    </div>
</div>

Nop.Plugin.Misc.FacebookShop/Views/Search.cshtml
@model SearchModel
@using Nop.Plugin.Misc.FacebookShop.Models;
@using Nop.Web.Extensions
@{
    Layout = "~/Plugins/Misc.FacebookShop/Views/Layout.cshtml";
}
<div class="page search-page">
    <div class="page-title">
        <h1>@T("Search")</h1>
    </div>
    <div class="page-body">
        <div class="search-input">
            @using (Html.BeginRouteForm("Plugin.Misc.FacebookShop.ProductSearch", FormMethod.Get))
            {
                <div class="inputs">
                    @Html.TextBoxFor(model => model.Q, new { @class = "search-text" })
                </div>
                <div class="buttons">
                    <input type="submit" class="button-1 search-button" value="@T("Search.Button")" />
                </div>
                if (!String.IsNullOrEmpty(Model.Warning))
                {
                <strong class="warning">
                    @Model.Warning
                </strong>
                }
            }
        </div>
        <div class="search-results">
            @if (Model.NoResults)
            {
                <strong class="result">
                    @T("Search.NoResultsText")
                </strong>
            }
            @if (Model.Products.Count > 0)
            {
                <div class="product-grid">
                    @foreach (var product in Model.Products)
                    {
                        <div class="item-box">
                            @Html.Partial("~/Plugins/Misc.FacebookShop/Views/ProductBox.cshtml", product)
                        </div>
                    }
                </div>
            }
            <div class="pager">
                @Html.Pager(Model.PagingFilteringContext).QueryParam("pagenumber").BooleanParameterName("as").BooleanParameterName("isc").BooleanParameterName("sid").RenderEmptyParameters(true)
            </div>
        </div>
    </div>
</div>

Nop.Plugin.Misc.FacebookShop/Views/SearchBox.cshtml
@using (Html.BeginRouteForm("Plugin.Misc.FacebookShop.ProductSearch", FormMethod.Get))
{
    <input type="text" class="search-box-text" autocomplete="off" name="q" placeholder="@T("Search.SearchBox.Tooltip")" />
    <input type="submit" class="button-1 search-box-button" value="@T("Search.Button")" />
}

Nop.Plugin.Misc.FacebookShop/Views/_RenderCategoryLine.cshtml
@model Nop.Plugin.Misc.FacebookShop.Models.RenderCategoryLineModel

<li @(Model.LastItem ? Html.Raw(" class=\"last\"") : null)>
    <a href="@Url.RouteUrl("Plugin.Misc.FacebookShop.Category", new { categoryId = Model.Category.Id })">@Model.Category.Name</a>
    @{
        var levelClass = "";
        if (Model.Level == 0)
        {
            levelClass = "firstLevel";
            <div class="top-menu-triangle"></div>
        }
        if (Model.Category.SubCategories.Count > 0)
        {
            <ul class="sublist @levelClass">
                @for (var i = 0; i < Model.Category.SubCategories.Count; i++)
                {
                    var subCategory = Model.Category.SubCategories[i];
                    //@RenderCategoryLine(subCategory, level + 1, )
                    @await Component.InvokeAsync("RenderCategoryLine", new { category = subCategory, level = Model.Level + 1, lastItem = i == Model.Category.SubCategories.Count - 1 })
                }
            </ul>
        }
    }
</li>